spring:
  application:
    name: bookstore-ddd

  # PostgreSQL 配置
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: zhangjiajun
    password:
    driver-class-name: org.postgresql.Driver

  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  # Flyway 配置
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    out-of-order: false

# 请求日志
logging:
  level:
    org.springframework.web: DEBUG
    com.example.demo: DEBUG

# 服务器端口
server:
  port: 8081

# JWT 配置
jwt:
  secret: WScgxcjaQRt3AKZwOB1nBPRjcl+dqXiywDgXtjPDXcY=
  expiration-ms: 86400000